### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by taimaiduc** [EldinZenderink/SubPlayerJS#2]
Cannot read property 'split' of undefined
    at String.<anonymous> (video.js:517)

**Comment by EldinZenderink** [comment]
Hi,

Sorry, but I don't think that's an issue related to SubPlayerJS, video.js is never used within subplayerjs, maybe it's another library that you are using? 

That said, I haven't done any development lately on subplayerjs and it's definitely not ready for production use, therefor I highly suggest to seek a alternative to this.

I might pick up development in the future but I don't really have the time for it.

**Comment by MasoudRahmani** [comment]
new pull request can solve this issue.
https://github.com/EldinZenderink/SubPlayerJS/pull/4

**Comment by MasoudRahmani** [comment]
with this pull https://github.com/EldinZenderink/SubPlayerJS/pull/6 the problem can be solved.
